# Site
 repository: sproogen/resume-theme
<<<<<<< HEAD
# favicon: images/favico232323n.ico

# Personal info
name: 钟学圣
title: PM
email: boyzhxsh@hotmail.com
phone: '18896606853'

=======
 # favicon: images/profile.jpg

# Personal info
 name: 钟学圣
 title: 产品经理
 email: boyzhxsh@hotmail.com
 website: https://blog.zhxshld.club/
>>>>>>> parent of e29af29... Update _config.yml

# Social links
# twitter_username: facespics
# github_username:  sproogen
#  dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
about_title: 个人介绍
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

<<<<<<< HEAD
  I am most skilled in: <mark>Axure</mark> and <mark>office</mark>
=======
  ceshiceshi112221
>>>>>>> parent of e29af29... Update _config.yml

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: 部分项目体验地址
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.baidu.com)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
